services:
  store_manager:
    build: .
    volumes:
      - .:/app
    environment:
      PYTHONPATH: /app/src
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: labo02
      DB_PASSWORD: labo02
      DB_NAME: labo02_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - redis

  tests:
    build: .
    volumes:
      - .:/app
    working_dir: /app/src
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: labo02
      DB_PASSWORD: labo02
      DB_NAME: labo02_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    depends_on:
      - mysql
      - redis
    command: python -m pytest

  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: labo02_db
      MYSQL_USER: labo02
      MYSQL_PASSWORD: labo02
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  mysql_data:
